config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:create, :index , :show, :edit ,:update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
  
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permited_parameters, if: :devise_controller?

  protected

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    book = Book.new(book_params)
    book.save
    redirect_to books_path
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
  end

  def edit
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
       <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
          <table class = "table">
            <tbody>
              <tr>
                 <th scope="row">name</th>
                 <td><%= @user.name %></td>
              </tr>
              <tr>
                 <th scope="row">introduction</th>
                 <th><%= @user.introduction %></th>
              </tr>
            </tbody>
           </table>

        <a class = "btn btn-outline-secondary btn-block">
           <i class="fas fa-users-cog"></i>
        </a>

        <h2>New book</h2>
        <%= form_with model: @book, local:true do |f| %>
          <div class = "field">
            <%= f.label :title %><br />
            <%= f.text_field :title %>
          </div>
          <div class = "field">
            <%= f.label :body %><br />
            <%= f.text_area :body %>
          </div>
          <div class = "actions">
            <%= f.submit "Create Book", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>

      <div class = "col-md-8 offset-md-1 ">
        <h2>Books</h2>
        <table class = "table table-hover">
           <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Opinion</th>
                <th colspan="3"></th>
               </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
               <tr>
                 <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
                 <td><%= link_to book.title, book_path(book.id) %></td>
                 <td><%= book.body %></td>
               </tr>
            <% end %>
            </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class = "container">
  <div class = "row">
    <h3>User info</h3>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class = "table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <h2>New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
        <div class = "field">
          <%= f.label :title %><br />
          <%= f.text_field :title %>
        </div>
        <div class = "field">
          <%= f.label :body %><br />
          <%= f.text_area :body %>
        </div>
        <div class = "actions">
          <%= f.submit "Create Book" %>
        </div>
        <% end %>

      <h2>Book detail</h2>
      <div class = "table">
        <tbody>
          <tr>
             <td>
               <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
               <%= @book.user.name %>
             </td>
             <td><%= @book.title %></td>
             <td><%= @book.body %></td>
          </tr>
        </tbody>
      </div>
  </div>
</div>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/fba08a387b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        Home
      </li>
      <li>
        Users
      </li>
      <li>
        <%= link_to 'Books', books_path %>
      </li>
      <li>
        <%= link_to 'logout', destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        Home
      </li>
      <li>
        About
      </li>
      <li>
        <%= link_to 'sign up', new_user_registration_path %>
      </li>
      <li>
        <%= link_to 'login', new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>